version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "49160:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db